Add routes
heintayzar-hm/blog pull request #4
Opened 2023-02-27 15:58 UTC by heintayzar-hm

-  **Important:** do NOT use `rails generate scaffold` command. The point of this project is to show you how to set up controllers by yourself.
-  Take a look at the wireframes below. Make sure that your app handles the URLs used in the wireframes:  

<p align="center">
  <img src="../images/blog_root_users.png" alt="All users page wireframe"  width="200px"  />
  <img src="../images/blog_user_page.png" alt="Single user page wireframe"  width="200px"  />
  <img src="../images/blog_user_all_posts.png" alt="All posts by a given user page wireframe"  width="200px"  />
  <img src="../images/blog_single_post.png" alt="Single post page wireframe"  width="200px"  />
</p>

-  For each URL you should create:
    - A route.
    - An action in the correct controller.
    - A view file.

-  View files should include only placeholders written in plain HTML, e.g:
    - Here is a list of posts for a given user

-  Make sure that you added code to handle **only** the 4 required URLs.

2023-02-27 17:00 UTC, zieeco requested changes
Hi @heintayzar-hm ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice controller setup. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-27 17:00 UTC, zieeco commented on config/routes.rb
> +  get 'users/:user_id/posts', to: 'posts#index', as: 'user_posts'
- Hey, currently when try changing your routes, it does not work as expected. each should take you to the corresponding routes as shown in the wireframe. as of now, it doesn't work. please, kindly fix the issues from your user `index`, user `show` and post `index`, and post `show` `.erb` files to fix this error.

:point_right: [OPTIONAL] Also, you can specify which route you want to show instead of implicitly stating as you've done. a better approach could be

```
resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
```
:point_up: ... end of OPTIONAL.. :point_left: 



*Here's how your routes are meant to work in the wireframe*
![routes](https://user-images.githubusercontent.com/59397159/221627245-f4cb70ff-8d7a-439d-9d5a-3d7c4eff6274.png)

e.g index page for user = `http://127.0.0.1:3000/users`
user show page = `http://127.0.0.1:3000/users/1`
post index page of a user = `http://127.0.0.1:3000/users/1/posts` 
post show page of a user = `http://127.0.0.1:3000/users/1/posts/1`

2023-02-27 18:58 UTC, heintayzar-hm commented on config/routes.rb
> +  get 'users/:user_id/posts', to: 'posts#index', as: 'user_posts'
Isn't it supposed to be like that? On wireframe,
Note: The first one is only / not contain /users
index page for user = http://127.0.0.1:3000/
user show page = http://127.0.0.1:3000/users/1
post index page of a user = http://127.0.0.1:3000/users/1/posts
post show page of a user = http://127.0.0.1:3000/users/1/posts/1

And also are you sure the error is from that. Not from not setting up database and adding dummy data?

My side:
![Screenshot from 2023-02-28 01-24-37](https://user-images.githubusercontent.com/105173981/221656730-f06c4caf-4055-4d37-9674-04e3a396c268.png)

![Screenshot from 2023-02-28 01-24-16](https://user-images.githubusercontent.com/105173981/221656755-a375c223-b440-42a2-a66d-62b190cf3a2f.png)

![Screenshot from 2023-02-28 01-23-42](https://user-images.githubusercontent.com/105173981/221656765-b485108f-b64e-476f-96cf-17a5315f4584.png)

![Screenshot from 2023-02-28 01-23-06](https://user-images.githubusercontent.com/105173981/221656779-2577a969-b1cb-498e-8c7c-396d12ae2e70.png)

2023-02-27 19:13 UTC, heintayzar-hm commented on config/routes.rb
> +  get 'users/:user_id/posts', to: 'posts#index', as: 'user_posts'
I added some default calls to db in view so that I could use that code later. Is that the problem?

2023-02-27 19:53 UTC, zieeco commented on config/routes.rb
> +  get 'users/:user_id/posts', to: 'posts#index', as: 'user_posts'
@heintayzar-hm, My bad! I didn't add any users to the database. if that's the case, kindly re-submit for another review!

2023-02-27 19:57 UTC, heintayzar-hm commented on config/routes.rb
> +  get 'users/:user_id/posts', to: 'posts#index', as: 'user_posts'
I am just confirming things because I don't know whether that is the issue. That is not needed in your review list anyway. Sorry for trouble.

2023-02-27 20:02 UTC, zieeco commented on config/routes.rb
> +  get 'users/:user_id/posts', to: 'posts#index', as: 'user_posts'
@heintayzar-hm, That's why I pointed out that optional. The only concern is the index and show pages. It's an oversight from my end as I didn't seed the database with any data> My bad! 
Since it works as expected from your end, Please, re-submit for another review. 
I'm sorry for any inconveniences this might have caused you! 
:pray:

2023-02-28 11:42 UTC, gemmen29 approved these changes
Hi @heintayzar-hm, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 11:53 UTC, merged